# Generated by Django 3.1.7 on 2021-03-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('version', models.CharField(max_length=30, verbose_name='项目版本')),
                ('type', models.CharField(choices=[('1', 'APP'), ('2', 'WEB')], max_length=30)),
                ('description', models.CharField(default='这个人很懒，不想写描述', max_length=50, verbose_name='项目描述')),
                ('last_edit_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('status', models.CharField(choices=[('1', '项目可用'), ('2', '项目不可用')], default=1, max_length=20, verbose_name='项目状态')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Apimodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=30, verbose_name='接口名称')),
                ('url', models.CharField(max_length=50, verbose_name='接口路径')),
                ('api_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('flag', models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口')),
                ('request_data', models.CharField(max_length=200, verbose_name='请求参数')),
                ('last_edit_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.projectmodel')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'db_table': 'api',
            },
        ),
    ]
