# Generated by Django 3.1.7 on 2021-03-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0002_auto_20210304_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='project',
            new_name='project_id',
        ),
    ]
