# Generated by Django 3.1.7 on 2021-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0005_auto_20210304_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
    ]
