# Generated by Django 3.1.7 on 2021-03-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0007_auto_20210304_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimodel',
            name='project',
        ),
        migrations.AddField(
            model_name='apimodel',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.projectmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('1', '执行'), ('2', '不执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
    ]
