# Generated by Django 3.1.7 on 2021-03-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0008_auto_20210304_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimodel',
            name='project_id',
        ),
        migrations.AddField(
            model_name='apimodel',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.projectmodel', verbose_name='接口所属于的项目'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
    ]
