# Generated by Django 3.1.7 on 2021-03-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0009_auto_20210304_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('1', '有效'), ('2', '已删除')], default=1, max_length=10, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('1', '执行'), ('2', '不执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
    ]
