# Generated by Django 3.1.7 on 2021-03-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0011_auto_20210305_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.CreateModel(
            name='BaseUrlModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_url', models.CharField(max_length=30, verbose_name='根域名')),
                ('status', models.CharField(choices=[('2', '已删除'), ('1', '有效')], max_length=10, verbose_name='是否有效')),
                ('last_edit_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.projectmodel', verbose_name='属于那个项目')),
            ],
            options={
                'verbose_name': '跟域名',
                'verbose_name_plural': '跟域名',
                'db_table': 'base_url',
            },
        ),
    ]
