# Generated by Django 3.1.7 on 2021-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0013_auto_20210305_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseurlmodel',
            name='url_name',
            field=models.CharField(default=1, max_length=30, verbose_name='跟域名名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('1', '有效'), ('2', '已删除')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('1', '有效'), ('2', '已删除')], max_length=10, verbose_name='是否有效'),
        ),
    ]
