# Generated by Django 3.1.7 on 2021-03-07 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0016_auto_20210305_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseurlmodel',
            options={'verbose_name': '根域名', 'verbose_name_plural': '根域名'},
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='ApiTestSummaryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b3bc165d-3dbb-4ce9-ab95-ce36f1a8243c'), editable=False, primary_key=True, serialize=False)),
                ('success_amount', models.IntegerField(verbose_name='成功数量')),
                ('fail_amount', models.IntegerField(verbose_name='错误数量')),
                ('skip_amoumt', models.IntegerField(verbose_name='跳过数量')),
                ('test_start_time', models.CharField(max_length=255, verbose_name='测试开始的时间')),
                ('test_spend_time', models.CharField(max_length=255, verbose_name='测试花费的时间')),
                ('test_case_amoumt', models.IntegerField(verbose_name='测试用例数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.baseurlmodel', verbose_name='对应的根域名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.projectmodel', verbose_name='所属的项目')),
            ],
            options={
                'verbose_name': '测试结果概要',
                'verbose_name_plural': '测试结果概要',
                'db_table': 'api_test_summary',
            },
        ),
        migrations.CreateModel(
            name='ApiTestResultModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a2dcbb0e-62e4-4094-85a7-e97bffb6af18'), primary_key=True, serialize=False)),
                ('test_path', models.CharField(max_length=255, verbose_name='测试的路径')),
                ('test_status', models.CharField(choices=[('2', '失败'), ('3', '跳过'), ('1', '成功')], max_length=255, verbose_name='测试结果')),
                ('test_description', models.CharField(max_length=255, verbose_name='测试描述')),
                ('fail_reason', models.CharField(max_length=1000, verbose_name='错误原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('summary_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.apitestsummarymodel')),
            ],
            options={
                'verbose_name': '详细测试结果',
                'verbose_name_plural': '详细测试结果',
                'db_table': 'api_test_result',
            },
        ),
    ]
