# Generated by Django 3.1.7 on 2021-03-07 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0017_auto_20210307_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('1', '执行'), ('2', '不执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0f944d72-6679-4a73-bfa8-790b57df6549'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b4355eb-9c2d-4e93-b2d4-bef1c507b529'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], max_length=10, verbose_name='是否有效'),
        ),
    ]
