# Generated by Django 3.1.7 on 2021-03-07 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0019_auto_20210307_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34065829-8ff1-4b67-86a5-f278fca32b18'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('2', '失败'), ('3', '跳过'), ('1', '成功')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79996e78-86db-450a-a9f9-948f8d0832c3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
