# Generated by Django 3.1.7 on 2021-03-07 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0020_auto_20210307_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7c92e5e-c5da-43fb-94fc-841425fd9ffa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('3', '跳过'), ('1', '成功'), ('2', '失败')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa62b319-d187-46be-934a-71dc56696990'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], max_length=10, verbose_name='是否有效'),
        ),
    ]
