# Generated by Django 3.1.7 on 2021-03-08 03:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0021_auto_20210307_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestsummarymodel',
            old_name='skip_amoumt',
            new_name='skip_amount',
        ),
        migrations.RenameField(
            model_name='apitestsummarymodel',
            old_name='test_case_amoumt',
            new_name='test_case_amount',
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('1', '执行'), ('2', '不执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('1', '有效'), ('2', '已删除')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d0aa0da-83b8-470e-b0c8-f1d49aa20a0c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('1', '成功'), ('2', '失败'), ('3', '跳过')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cafc3066-c603-48e5-b485-cd1bbb1e8d24'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('1', '有效'), ('2', '已删除')], max_length=10, verbose_name='是否有效'),
        ),
    ]
