# Generated by Django 3.1.7 on 2021-03-08 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0022_auto_20210308_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitestresultmodel',
            old_name='summary_id',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7321abcf-b7a6-4d17-8e3a-4635dea4510b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('3', '跳过'), ('1', '成功'), ('2', '失败')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0f63c3c-7d29-4106-b6fc-8ceb302c617a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
