# Generated by Django 3.1.7 on 2021-03-08 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0023_auto_20210308_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('1', '执行'), ('2', '不执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88b41828-b1d1-41ff-bbf8-f257641b7833'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='summary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.apitestsummarymodel'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('1', '成功'), ('3', '跳过'), ('2', '失败')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41cdb246-a324-4e29-bb3d-3624aa7d54f3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
