# Generated by Django 3.1.7 on 2021-03-08 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0024_auto_20210308_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0d9952c-08f9-40de-acc2-8abaf64c209e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_man.apitestsummarymodel'),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4d2157d-27b4-45c8-bfc8-c9996061643b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], max_length=10, verbose_name='是否有效'),
        ),
    ]
