# Generated by Django 3.1.7 on 2021-03-08 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0025_auto_20210308_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4314f8a1-77b5-4dc0-afbc-b099752c398a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('3', '跳过'), ('1', '成功'), ('2', '失败')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apitestsummarymodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b9481f9-6154-4740-a00f-eb2e6b3ddf77'), editable=False, primary_key=True, serialize=False),
        ),
    ]
