# Generated by Django 3.1.7 on 2021-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0027_auto_20210310_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='request_data',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='fail_reason',
            field=models.CharField(max_length=10000, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('3', '跳过'), ('1', '成功'), ('2', '失败')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], max_length=10, verbose_name='是否有效'),
        ),
    ]
