# Generated by Django 3.1.7 on 2021-03-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0028_auto_20210311_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('1', '执行'), ('2', '不执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='fail_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('2', '失败'), ('3', '跳过'), ('1', '成功')], max_length=255, verbose_name='测试结果'),
        ),
    ]
