# Generated by Django 3.1.7 on 2021-03-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0029_auto_20210311_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('2', '不执行'), ('1', '执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('1', '有效'), ('2', '已删除')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('1', '成功'), ('2', '失败'), ('3', '跳过')], max_length=255, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('1', '有效'), ('2', '已删除')], max_length=10, verbose_name='是否有效'),
        ),
    ]
