# Generated by Django 3.1.7 on 2021-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0030_auto_20210311_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], default=1, max_length=20, verbose_name='接口状态'),
        ),
        migrations.AlterField(
            model_name='baseurlmodel',
            name='status',
            field=models.CharField(choices=[('2', '已删除'), ('1', '有效')], max_length=10, verbose_name='是否有效'),
        ),
    ]
