# Generated by Django 3.1.7 on 2021-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_man', '0031_auto_20210311_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apimodel',
            options={'ordering': ['-create_time'], 'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='flag',
            field=models.CharField(choices=[('1', '执行'), ('2', '不执行')], max_length=10, verbose_name='是否执行该接口'),
        ),
        migrations.AlterField(
            model_name='apitestresultmodel',
            name='test_status',
            field=models.CharField(choices=[('1', '成功'), ('3', '跳过'), ('2', '失败')], max_length=255, verbose_name='测试结果'),
        ),
    ]
